spring.application.name=pet-guardian

# Oracle Database
spring.datasource.url=${ORACLE_URL}
spring.datasource.username=${ORACLE_USER}
spring.datasource.password=${ORACLE_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none

# MongoDB (Railway NoSQL)
spring.data.mongodb.uri=${MONGO_URL}

# Flyway (Desabilitado por padrão na base gerenciada FIAP onde as tabelas já foram criadas via DDL oficial)
spring.flyway.enabled=${SPRING_FLYWAY_ENABLED:false}

# Actuator / Info
info.app.name=Pet Guardian
info.app.description=API para o projeto PetGuardian
info.app.version=1.0.0

management.endpoints.web.exposure.include=health,info,metrics,caches
management.endpoint.health.show-details=always
springdoc.swagger-ui.operationsSorter=method
spring.jpa.show-sql=true

# RSA Keys (JWT)
rsa.private-key=${RSA_PRIVATE_KEY:classpath:keys/private_key.pem}
rsa.public-key=${RSA_PUBLIC_KEY:classpath:keys/public_key.pem}

server.port=${PORT:8080}
server.forward-headers-strategy=framework

# Timezone
spring.jackson.time-zone=America/Sao_Paulo

spring.docker.compose.enabled=false
