CREATE SEQUENCE IF NOT EXISTS revinfo_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE aula
(
    id_aula          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome             VARCHAR(50)                             NOT NULL,
    descricao        VARCHAR(100)                            NOT NULL,
    pontos_aula      INTEGER                                 NOT NULL,
    dificuldade      VARCHAR(20)                             NOT NULL,
    conteudo         VARCHAR(1000)                           NOT NULL,
    concluida        BOOLEAN                                 NOT NULL,
    modulo_id_modulo BIGINT                                  NOT NULL,
    CONSTRAINT pk_aula PRIMARY KEY (id_aula)
);

CREATE TABLE bairro
(
    id_bairro        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome_bairro      VARCHAR(30)                             NOT NULL,
    cidade_id_cidade BIGINT                                  NOT NULL,
    CONSTRAINT pk_bairro PRIMARY KEY (id_bairro)
);

CREATE TABLE cidade
(
    id_cidade        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome_cidade      VARCHAR(30)                             NOT NULL,
    estado_id_estado BIGINT                                  NOT NULL,
    CONSTRAINT pk_cidade PRIMARY KEY (id_cidade)
);

CREATE TABLE endereco
(
    id_endereco      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cep              VARCHAR(8)                              NOT NULL,
    numero           VARCHAR(5)                              NOT NULL,
    rua              VARCHAR(150)                            NOT NULL,
    bairro_id_bairro BIGINT                                  NOT NULL,
    CONSTRAINT pk_endereco PRIMARY KEY (id_endereco)
);

CREATE TABLE estado
(
    id_estado   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome_estado VARCHAR(30)                             NOT NULL,
    CONSTRAINT pk_estado PRIMARY KEY (id_estado)
);

CREATE TABLE historico
(
    id_hist    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tipo_hist  VARCHAR(30)                             NOT NULL,
    data_hist  TIMESTAMP(6) WITHOUT TIME ZONE          NOT NULL,
    pet_id_pet BIGINT                                  NOT NULL,
    CONSTRAINT pk_historico PRIMARY KEY (id_hist)
);

CREATE TABLE modulo
(
    id_modulo        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome             VARCHAR(50)                             NOT NULL,
    tempo_conclusao  VARCHAR(10)                             NOT NULL,
    descricao        VARCHAR(100)                            NOT NULL,
    trilha_id_trilha BIGINT                                  NOT NULL,
    CONSTRAINT pk_modulo PRIMARY KEY (id_modulo)
);

CREATE TABLE pet
(
    id_pet       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome         VARCHAR(30)                             NOT NULL,
    data_nasc    date                                    NOT NULL,
    raca_id_raca BIGINT                                  NOT NULL,
    porte        VARCHAR(10)                             NOT NULL,
    sexo         CHAR                                    NOT NULL,
    castrado     BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_pet PRIMARY KEY (id_pet)
);

CREATE TABLE raca
(
    id_raca   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome_raca VARCHAR(30)                             NOT NULL,
    CONSTRAINT pk_raca PRIMARY KEY (id_raca)
);

CREATE TABLE revchanges
(
    rev        BIGINT NOT NULL,
    entityname VARCHAR(255)
);

CREATE TABLE revinfo
(
    rev      BIGINT NOT NULL,
    revtstmp BIGINT,
    CONSTRAINT pk_revinfo PRIMARY KEY (rev)
);

CREATE TABLE status
(
    id_status   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome_status VARCHAR(15)                             NOT NULL,
    CONSTRAINT pk_status PRIMARY KEY (id_status)
);

CREATE TABLE tarefa
(
    id_tarefa          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    titulo             VARCHAR(30)                             NOT NULL,
    pontos_tarefa      INTEGER                                 NOT NULL,
    descricao          VARCHAR(200)                            NOT NULL,
    criacao            TIMESTAMP(6) WITHOUT TIME ZONE          NOT NULL,
    prazo              TIMESTAMP(6) WITHOUT TIME ZONE          NOT NULL,
    conclusao          TIMESTAMP(6) WITHOUT TIME ZONE,
    status_id_status   BIGINT                                  NOT NULL,
    usuario_id_usuario BIGINT                                  NOT NULL,
    pet_id_pet         BIGINT                                  NOT NULL,
    CONSTRAINT pk_tarefa PRIMARY KEY (id_tarefa)
);

CREATE TABLE telefone
(
    id_telefone BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    num_ddd     VARCHAR(2)                              NOT NULL,
    num_tel     VARCHAR(9)                              NOT NULL,
    CONSTRAINT pk_telefone PRIMARY KEY (id_telefone)
);

CREATE TABLE trilha
(
    id_trilha  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome       VARCHAR(30)                             NOT NULL,
    descricao  VARCHAR(200)                            NOT NULL,
    pet_id_pet BIGINT                                  NOT NULL,
    CONSTRAINT pk_trilha PRIMARY KEY (id_trilha)
);

CREATE TABLE usuario
(
    id_usuario           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome                 VARCHAR(100)                            NOT NULL,
    email                VARCHAR(50)                             NOT NULL,
    senha                VARCHAR(60)                             NOT NULL,
    role                 VARCHAR(10)                             NOT NULL,
    telefone_id_telefone BIGINT                                  NOT NULL,
    CONSTRAINT pk_usuario PRIMARY KEY (id_usuario)
);

CREATE TABLE usuario_endereco
(
    endereco_id_endereco BIGINT NOT NULL,
    usuario_id_usuario   BIGINT NOT NULL,
    CONSTRAINT pk_usuario_endereco PRIMARY KEY (endereco_id_endereco, usuario_id_usuario)
);

CREATE TABLE usuario_pet
(
    respon_princ       BOOLEAN NOT NULL,
    usuario_id_usuario BIGINT  NOT NULL,
    pet_id_pet         BIGINT  NOT NULL,
    CONSTRAINT pk_usuario_pet PRIMARY KEY (usuario_id_usuario, pet_id_pet)
);

ALTER TABLE raca
    ADD CONSTRAINT uc_raca_nome_raca UNIQUE (nome_raca);

ALTER TABLE status
    ADD CONSTRAINT uc_status_nome_status UNIQUE (nome_status);

ALTER TABLE usuario
    ADD CONSTRAINT uc_usuario_email UNIQUE (email);

ALTER TABLE aula
    ADD CONSTRAINT FK_AULA_ON_MODULO_ID_MODULO FOREIGN KEY (modulo_id_modulo) REFERENCES modulo (id_modulo);

ALTER TABLE bairro
    ADD CONSTRAINT FK_BAIRRO_ON_CIDADE_ID_CIDADE FOREIGN KEY (cidade_id_cidade) REFERENCES cidade (id_cidade);

ALTER TABLE cidade
    ADD CONSTRAINT FK_CIDADE_ON_ESTADO_ID_ESTADO FOREIGN KEY (estado_id_estado) REFERENCES estado (id_estado);

ALTER TABLE endereco
    ADD CONSTRAINT FK_ENDERECO_ON_BAIRRO_ID_BAIRRO FOREIGN KEY (bairro_id_bairro) REFERENCES bairro (id_bairro);

ALTER TABLE historico
    ADD CONSTRAINT FK_HISTORICO_ON_PET_ID_PET FOREIGN KEY (pet_id_pet) REFERENCES pet (id_pet);

ALTER TABLE modulo
    ADD CONSTRAINT FK_MODULO_ON_TRILHA_ID_TRILHA FOREIGN KEY (trilha_id_trilha) REFERENCES trilha (id_trilha);

ALTER TABLE pet
    ADD CONSTRAINT FK_PET_ON_RACA_ID_RACA FOREIGN KEY (raca_id_raca) REFERENCES raca (id_raca);

ALTER TABLE tarefa
    ADD CONSTRAINT FK_TAREFA_ON_PET_ID_PET FOREIGN KEY (pet_id_pet) REFERENCES pet (id_pet);

ALTER TABLE tarefa
    ADD CONSTRAINT FK_TAREFA_ON_STATUS_ID_STATUS FOREIGN KEY (status_id_status) REFERENCES status (id_status);

ALTER TABLE tarefa
    ADD CONSTRAINT FK_TAREFA_ON_USUARIO_ID_USUARIO FOREIGN KEY (usuario_id_usuario) REFERENCES usuario (id_usuario);

ALTER TABLE trilha
    ADD CONSTRAINT FK_TRILHA_ON_PET_ID_PET FOREIGN KEY (pet_id_pet) REFERENCES pet (id_pet);

ALTER TABLE usuario
    ADD CONSTRAINT FK_USUARIO_ON_TELEFONE_ID_TELEFONE FOREIGN KEY (telefone_id_telefone) REFERENCES telefone (id_telefone);

ALTER TABLE usuario_pet
    ADD CONSTRAINT FK_USUARIO_PET_ON_PET_ID_PET FOREIGN KEY (pet_id_pet) REFERENCES pet (id_pet);

ALTER TABLE usuario_pet
    ADD CONSTRAINT FK_USUARIO_PET_ON_USUARIO_ID_USUARIO FOREIGN KEY (usuario_id_usuario) REFERENCES usuario (id_usuario);

ALTER TABLE revchanges
    ADD CONSTRAINT fk_revchanges_on_default_tracking_modified_entities_changelog FOREIGN KEY (rev) REFERENCES revinfo (rev);

ALTER TABLE usuario_endereco
    ADD CONSTRAINT fk_usuend_on_endereco FOREIGN KEY (endereco_id_endereco) REFERENCES endereco (id_endereco);

ALTER TABLE usuario_endereco
    ADD CONSTRAINT fk_usuend_on_usuario FOREIGN KEY (usuario_id_usuario) REFERENCES usuario (id_usuario);